import './globals.css'
import ThemeRegistry from "../../theme/ThemeRegistry";
import {Inter} from 'next/font/google'
import React from "react";

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: "create Next App",
  description: "Generated by create next app"
};


export default function RootLayout({children,}: {
  children: React.ReactNode
}) {
  return (
      <ThemeRegistry>
          <html lang="en">
          <body className={inter.className} suppressHydrationWarning={true}>{children}</body>
          </html>
      </ThemeRegistry>
  )
}